# Usando a imagem oficial do .NET 6.0 SDK para buildar a aplicação
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

# Copiar o arquivo .csproj e restaurar as dependências
COPY *.csproj ./
RUN dotnet restore

# Copiar o restante dos arquivos e buildar a aplicação
COPY . ./
RUN dotnet publish -c Release -o /out

# Usando a imagem runtime do .NET para rodar a aplicação
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build /out .

# Expor a porta padrão
EXPOSE 80

# Definir o ponto de entrada da aplicação
ENTRYPOINT ["dotnet", "LanchesMac.dll"]
